#!/usr/bin/env python3
"""
Competitive Exam Daily Notes — AI-Powered
Scrapes news, analyzes with Gemini 1.5 Pro, generates HTML notes, sends to Telegram.
"""

import os
import sys
import argparse
from datetime import datetime

# Ensure NLTK data
import nltk
try:
    nltk.data.find('tokenizers/punkt')
except LookupError:
    nltk.download('punkt', quiet=True)

from ai_scraper import AIExamNewsScraper
from html_generator import HTMLNotesGenerator
from telegram_sender import TelegramSender
from config import HTML_OUTPUT_PATH, NOTES_TITLE


def main():
    parser = argparse.ArgumentParser(description='AI-Powered Exam Daily Notes')
    parser.add_argument('--html-only', action='store_true', help='Only generate HTML, skip Telegram')
    parser.add_argument('--send-only', action='store_true', help='Only send existing HTML to Telegram')
    parser.add_argument('--output', type=str, default=HTML_OUTPUT_PATH)
    parser.add_argument('--title', type=str, default=NOTES_TITLE)
    args = parser.parse_args()

    print("=" * 65)
    print("   📰 AI-POWERED EXAM DAILY NOTES")
    print("   Gemini 1.5 Pro · Smart Classification · HTML Notes")
    print("=" * 65)

    if args.send_only:
        if not os.path.exists(args.output):
            print(f"❌ HTML file not found: {args.output}")
            sys.exit(1)
        sender = TelegramSender()
        sender.send_file_sync(
            args.output,
            filename=args.output.split('/')[-1]
        )
        return

    # Scrape + AI Analysis
    print("\n🔍 Scraping & AI-analyzing exam-relevant articles...")
    scraper = AIExamNewsScraper()
    categorized_articles = scraper.scrape_all()

    total = sum(len(v) for v in categorized_articles.values())
    if total == 0:
        print("❌ No relevant articles found.")
        sys.exit(1)

    print(f"\n📊 Final Summary:")
    for topic, arts in sorted(categorized_articles.items()):
        gemini_count = sum(1 for a in arts if a.get("gemini_processed"))
        print(f"   • {topic}: {len(arts)} articles ({gemini_count} AI-analyzed)")
    print(f"   Total: {total} articles")

    # Generate HTML Notes
    print(f"\n📝 Generating beautiful HTML notes...")
    html_gen = HTMLNotesGenerator(output_path=args.output)
    html_path = html_gen.generate(categorized_articles, title=args.title)

    # Send to Telegram
    if not args.html_only:
        print("\n📤 Sending to Telegram...")
        sender = TelegramSender()

        # Build smart caption with stats
        gs_counts = {}
        for topic, arts in categorized_articles.items():
            gs = arts[0].get("gs_paper", "General") if arts else "General"
            gs_counts[gs] = gs_counts.get(gs, 0) + len(arts)

        stats_lines = " | ".join([f"{gs}: {cnt}" for gs, cnt in sorted(gs_counts.items())])
        caption = (
            f"📰 <b>{args.title}</b>\n"
            f"📅 {datetime.now().strftime('%B %d, %Y')}\n"
            f"📊 {total} articles analyzed\n"
            f"🗂️ {stats_lines}\n\n"
            f"🤖 <i>Generated by Gemini 1.5 Pro</i>\n"
            f"💡 Open in browser for best experience"
        )

        success = sender.send_file_sync(
            html_path,
            caption=caption,
            filename=html_path.split('/')[-1]
        )

        if not success:
            print(f"\n⚠️  HTML saved locally: {os.path.abspath(html_path)}")
    else:
        print(f"\n📄 HTML saved: {os.path.abspath(html_path)}")

    print("\n" + "=" * 65)
    print("   ✅ Done! Open the HTML file in any browser.")
    print("=" * 65)


if __name__ == "__main__":
    main()
